version: '3.5'

services:
  #########################
  mongo:
    container_name: flixDB
    image: mongo:6
    restart: always
    hostname: ${MONGO_HOST_NAME}
    volumes:
      - ${MONGO_DATA}:/data/db
      - ${MONGO_DUMP}:/dump
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
    #   MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - ${MONGO_PORT}:27017
    networks:
      - flex-network
  ######################### only in prod: comment when dev
  app:
    container_name: flix-flex-api
    build:
      context: .
      dockerfile: ./dockerfile
    restart: always
    env_file: .env
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - flex-network
  #########################
  elasticsearch:
    container_name: flixElasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    hostname: ${ES_HOST_NAME}
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - ${ELASTICSEARCH_PORT}:9200
    networks:
      - flex-network
    volumes:
      - ${ELS_DATA}:/usr/share/elasticsearch/data
  #########################

networks:
  flex-network:
    driver: bridge
